
export default () => ({
    empresa: null,
    usuario: null,
    editBool: false,
    options: {},
    menu: null,
    producto: {},
    validate: {
        existe: true,
        limite: false,
        menu: false,
    },
    logo: {},
    dataRedes: {},
    openModalEmpresa: false,
    openModalProducto: false,
    openModalProducto: false,
    openModalAddShop: false,
    openModalShop: false,
    openModalTipoPago: false,
    openModalDatosPago: false,
    vvSelected: {},
    shop:[],
    tipoPago:{},
    tipoEntrega:{},
    tipoDetalle: {},
    isShop: false,
    isClean: false,
    isTipoData: false
})